### ISSUE TITLE
Deployment is done on first partition of default topic

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/zeebe#1111]
In preparation to https://github.com/zeebe-io/zeebe/issues/1077 we have to change the current deployment behavior. 

The deployment have to be done on the first partition of the default topic. The deployment has to be *pushed* to the other existing partitions. This makes it possible, to remove the async polling in the workflow instance stream processor and to remove the internal topic.

AT:

 - [x] default topic is always created (in the tests) https://github.com/zeebe-io/zeebe/issues/1114
- [x] deployment is always done on partition 1 (later again on partition 0 after removing internal system) https://github.com/zeebe-io/zeebe/issues/1115
 - [x] deployment is pushed to all other existing partitions of this topic https://github.com/zeebe-io/zeebe/issues/1116

blocks #1077

**Comment by menski** [comment]
> deployment is done if deployment is pushed to all partition successfully

A deployment is successful from the client perspective if the deployment event was committed and verified on the first partition. It does not wait for the push to all partitions, as partitions could be unavailable at the moment. The deployment and the push should be decoupled. Similar like the deployment and pull work at the moment.

**Comment by Zelldon** [comment]
Yes thanks. To clarify, Deployment CREATE command is written on the log. Stream processor read this command and verifies the deployment and after that the response is send back to the client. What I meant with `deployment is done ...` is that the Deployment CREATED event is written on the log after deployment was pushed to all other partitions. I think this is true right?
