### ISSUE TITLE
Add project lib dependencies to bom

### ISSUE THREAD

**Issue by menski** [zeebe-io/zeebe#475]
### Problem

During the release process all sub project dependencies have to be manually adjusted. This is a cumbersome task which is error-prone and time-consuming. 

### Idea

- All sub project versions are managed in the zb-bom as properties and in the dependency management section
- All projects will have the same version at least until we hit 1.0.0 to ease the release process, so the next version for all projects will be 0.4.0, except for zb-parent and zb-build-tools
- As no version has to be adjusted anymore we can automate the full release #474 
- The limitation is that we have to disable the snapshot check on the release process, so we have to ensure that we do not add SNAPSHOT dependencies of third party libraries

### Tasks

- [x] set all project versions to 0.4.0-SNAPSHOT (except for zb-parent)
- [x] create zb-bom which contains the properties/dependency management to parent and use `${project.version}` for sub project version
- [x] in every project import the zb-bom with version `${project.version}`
- [x] remove properties/dependency management from sub projects
- [x] adjust all release jobs to `-DignoreSnapshots` to prevent release to fail on snapshot check
- [x] teach developers that we should never add SNAPSHOT dependencies for third party libraries

**Comment by menski** [comment]
It seems that we can release zb-parent with zeebe dependencies which are not released yet. At least the jenkins job was successful without uploading artifacts.

**Comment by menski** [comment]
zb-parent is not a good solution as we would still have to adjust the zb-parent version in every project before the release. Instead a zb-bom could be used to fully automate the release.

**Comment by menski** [comment]
This issue should be done, but I will keep it open until I tested this assumptions by building a release.

**Comment by menski** [comment]
Seems to be working with the release pipeline so I close this issue for now
