### ISSUE TITLE
[Milestone] Improve cycle time

### ISSUE THREAD

**Issue by korthout** [zeebe-io/zeebe#5315]
**Description**

Although Zeebe is focussed on high throughput, for many users it is important that Zeebe offers a good performance concerning cycle time.

> Cycle time: The time elapsed from the beginning of a workflow until completed.

This milestone issue is to keep track of improvements to the cycle time. We'll do that by:
- [x] running benchmarks of different versions of Zeebe to find cycle time performance degradation #5132
- [x] running benchmarks with different configurations to find quick fixes to improve cycle time #5313
- [x] exposing RocksDB config options to allows users to optimise RocksDB for themselves #5279
- [x] profiling Zeebe under load from a benchmark to root cause the perceived slowness #5314
- [x] implement full support for memory mapped files #4274

**Comment by korthout** [comment]
Future work: #4879

**Comment by npepinpe** [comment]
Can we consider this done? If so please close :slightly_smiling_face:

**Comment by korthout** [comment]
Let's close this and open a new milestone issue if this becomes a bigger topic again at some later time.
